import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header/header";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dragon Ball APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="es">
        <body className={inter.className}>
          <Header />
          <div className="container">{children}</div>
          <div className="kame-house-img">
            <Image
              width={300}
              height={300}
              alt={`Kame House`}
              src={`/wallpaper-kame_house.webp`}></Image>
          </div>
        </body>
      </html>
    </>
  );
}
